version: '3'

services:
  web:
    image: course:1.0
    build: .
    command: ./runserver
    volumes:
      - ".:/course"
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:10.3
